services:

  # Postgres database
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=meow'
      - 'POSTGRES_PASSWORD=password1234'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    ports:
      - "5435:5432/tcp"
    expose:
      - 5432
    volumes:
      - "./pgdata:/var/lib/postgresql/data"

  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:latest
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101

  # Moteur Api
  moteur:
    build:
      context: ./moteur
      dockerfile: Dockerfile
    container_name: moteur
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/meow
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=broker:29092
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password1234

  # Frontend
  client1:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: client1
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - moteur
    environment:
      - SERVER_PORT=8081
      - MOTEUR_URL=http://moteur:8080/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:29092

  client2:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: client2
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - moteur
    environment:
      - SERVER_PORT=8082
      - MOTEUR_URL=http://moteur:8080/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:29092