services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=meow'
      - 'POSTGRES_PASSWORD=password1234'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    ports:
      - 5435:5432/tcp
    expose:
      - 5432
